//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FemalePyroModelManager.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FemalePyroModelManager.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap alaxe {
            get {
                object obj = ResourceManager.GetObject("alaxe", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charred Chainmail
        ///Crusaders Getup
        ///Hot Case
        ///Lunatics Leathers
        ///Maniacs Manacles
        ///North Polar Fleece
        ///Pyromancers Raiments
        ///Rail Spikes
        ///Soot Suit
        ///Space Diver
        ///Sub Zero Suit
        ///Sweet Smismass Sweater
        ///Tricksters Turnout Gear
        ///Voodoo Cursed Soul
        ///Wanderers Wear
        ///Water Waders.
        /// </summary>
        internal static string cosmetics {
            get {
                return ResourceManager.GetString("cosmetics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap dani {
            get {
                object obj = ResourceManager.GetObject("dani", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Color Similar to Slate
        ///A Deep Commitment to Purple
        ///A Distinctive Lack of Hue
        ///A Mann&apos;s Mint
        ///After Eight
        ///Aged Moustache Grey
        ///An Air of Debonair
        ///An Extraordinary Abundance of Tinge
        ///Australium Gold
        ///Balaclavas Are Forever
        ///Color No. 216-190-216
        ///Cream Spirit
        ///Dark Salmon Injustice
        ///Drably Olive
        ///Indubitably Green
        ///Mann Co. Orange
        ///Muskelmannbraun
        ///Noble Hatter&apos;s Violet
        ///Operator&apos;s Overalls
        ///Peculiarly Drab Tincture
        ///Pink as Hell
        ///Radigan Conagher Brown
        ///Team Spirit
        ///The Bitter Taste of Defeat and Lime [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string paints {
            get {
                return ResourceManager.GetString("paints", resourceCulture);
            }
        }
    }
}
